#!/bin/bash

# The canonical way to dump logs is through the script below,
# but this file is here for backwards compatibility.

# Without this file, we have no way of giving users a dump logs command
# that will work regardless of Bassline version.

sudo /opt/bassline-privileged/collect-debug-logs
